name: Run Rspec
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version:
          - "3.0"
          - "3.1"
          - "3.2"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download voicevox core
        run: |
          curl https://raw.githubusercontent.com/VOICEVOX/voicevox_core/main/scripts/downloads/download.sh -O
          chmod u+x ./download.sh
          ./download.sh -v 0.14.0-preview.3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true

      - name: Run Rspec
        run: |
          bundle exec rake spec
        env:
          LD_LIBRARY_PATH: voicevox_core
          VOICEVOX_OPEN_JTALK_DICT: voicevox_core/open_jtalk_dic_utf_8-1.11
