name: Run Rspec
on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        ruby_version:
          - "3.0"
          - "3.1"
          - "3.2"
        platform:
          - "ubuntu-latest"
          - "windows-latest"
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download voicevox core (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          curl https://github.com/VOICEVOX/voicevox_core/releases/download/0.14.0/download-windows-x64.exe -Lo download.exe
          ./download.exe

      - name: Download voicevox core (Ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          curl https://github.com/VOICEVOX/voicevox_core/releases/download/0.14.0/download-linux-x64 -Lo download
          chmod +x download
          ./download

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true

      - name: Run Rspec
        run: |
          bundle exec rake spec
        env:
          LD_LIBRARY_PATH: voicevox_core
          RUBY_DLL_PATH: voicevox_core
          VOICEVOX_OPEN_JTALK_DICT: voicevox_core/open_jtalk_dic_utf_8-1.11
