name: Run Rspec
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch release
        run: |
          curl https://api.github.com/repos/voicevox/voicevox_core/releases/latest \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -o latest_release.json
          jq -r '.assets[] | select(.name | contains("voicevox_core-linux-x64-cpu-")) | .browser_download_url' latest_release.json > latest_release_url.txt
          jq -r '.assets[] | select(.name | contains("voicevox_core-linux-x64-cpu-")) | .updated_at' latest_release.json > latest_release_date.txt

      - name: Load cache
        id: load-cache
        uses: actions/cache@v3
        with:
          path: vv_lib
          # NOTE: 最後のv1はインクリメントしてキャッシュを消す用
          # 更新時刻とURLが一致している場合は同一とみなす
          key: ${{ runner.os }}-${{ hashFiles('./latest_release_url.txt') }}-${{ hashFiles('./latest_release_date.txt') }}-v1

      - name: Download voicevox_core
        if: steps.load-cache.outputs.cache-hit != 'true'
        run: |
          cat latest_release_url.txt | \
            xargs wget -qO voicevox_core.zip
          unzip voicevox_core.zip
          mkdir vv_lib
          cp ./voicevox_core-linux-x64-cpu-*/*.so vv_lib

      # FIXME: voicevox_coreの同封ライブラリ周りが直されたら消す
      - name: Download external libraries
        if: steps.load-cache.outputs.cache-hit != 'true'
        run: |
          wget -q https://github.com/microsoft/onnxruntime/releases/download/v1.10.0/onnxruntime-linux-x64-1.10.0.tgz
          tar -xvf onnxruntime-linux-x64-1.10.0.tgz
          cp onnxruntime-linux-x64-1.10.0/lib/*.so* vv_lib

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true

      - name: Run Rspec
        run: |
          bundle exec rake spec
        env:
          LD_LIBRARY_PATH: vv_lib
