name: Run Rspec
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Download Voicevox
        run: |
          curl https://api.github.com/repos/voicevox/voicevox_core/releases/latest | \
            jq -r '.assets[] | select(.name | contains("voicevox_core-linux-x64-cpu-")) | .browser_download_url' | \
            xargs wget -O voicevox_core.zip
          unzip voicevox_core.zip
          cp ./voicevox_core-linux-x64-cpu-*/* .
    
      - name: Install dependencies
        run: |
          bundle install
      
      - name: Run Rspec
        run: |
          rake spec

      
